const locationForMovieLocation = {
  message: "successfully",
  result: [
    {
      AD_Instructions: "Romantic scenes with a bonfire",
      Area: "Not Applicable",
      Assigned_To: 11,
      Assigned_date: "Tue, 10 Oct 2023 13:00:00 GMT",
      Budget_Night: "4000",
      Budget_day: "3000",
      Category: "Historic",
      Country: "India",
      Created_By: 11,
      Created_on: "Tue, 10 Oct 2023 13:00:00 GMT",
      Location_Description: "Submarine turned museum in Vizag.",
      Location_Id: 11,
      Location_Name: "Vizag Submarine Museum",
      Location_Type: "Indoor",
      No_Of_Scenes: 4,
      Owner_details: "Indian Navy",
      Permissions: "Public Access",
      Photo_Path1: "path11.jpg",
      Photo_Path2: "path12.jpg",
      Photo_Path3: "path13.jpg",
      Photo_Path4: "path14.jpg",
      Photo_Path5: "path15.jpg",
      Previous_Films: "Ghazi",
      Production_id: 20,
      Record_Status: "Y",
      Scene_Id: 27,
      Scene_Location_Id: 11,
      Screen_Time_Minutes: 90,
      Shoot_Time_Minutes: 100,
      Special_requirements: "Beach sunset scene",
      Specification: "Submarine Museum",
      State: "Andhra Pradesh",
      Status: "Assigned",
    },
  ],
  status: 200,
};

exports.locationForMovieLocation = locationForMovieLocation;
