const tempLocationApproveData = {
  message: "successfully",
  result: [
    {
      Area: "Not Applicable",
      Assigned_To: 12.0,
      Assigned_date: "Mon, 02 Jan 2023 00:00:00 GMT",
      Budget_Night: "4000",
      Budget_day: "3000",
      Category: "Historic",
      Country: "India",
      Created_By: 12.0,
      Location_Description: "Submarine turned museum in Vizag.",
      Location_Id: 11,
      Location_Name: "Vizag Submarine Museum",
      Location_Type: "Indoor",
      Owner_details: "Indian Navy",
      Permissions: "Public Access",
      Photo_Path1: "path11.jpg",
      Photo_Path2: "path12.jpg",
      Photo_Path3: "path13.jpg",
      Photo_Path4: "path14.jpg",
      Photo_Path5: "path15.jpg",
      Previous_Films: "Ghazi",
      Record_Status: "Active",
      Specification: "Submarine Museum",
      State: "Andhra Pradesh",
      Status: "Available",
    },
    {
      Area: "Not Applicable",
      Assigned_To: 13.0,
      Assigned_date: "Mon, 16 Jan 2023 00:00:00 GMT",
      Budget_Night: "N/A",
      Budget_day: "N/A",
      Category: "University",
      Country: "India",
      Created_By: 13.0,
      Location_Description: "Prominent university in Hyderabad.",
      Location_Id: 12,
      Location_Name: "JNTU Hyderabad",
      Location_Type: "Educational",
      Owner_details: "JNTUH",
      Permissions: "Public Access",
      Photo_Path1: "path16.jpg",
      Photo_Path2: "path17.jpg",
      Photo_Path3: "path18.jpg",
      Photo_Path4: "path19.jpg",
      Photo_Path5: "path20.jpg",
      Previous_Films: "N/A",
      Record_Status: "Active",
      Specification: "Large University Campus",
      State: "Telangana",
      Status: "Available",
    },
    {
      Area: "Not Applicable",
      Assigned_To: 14.0,
      Assigned_date: "Mon, 02 Jan 2023 00:00:00 GMT",
      Budget_Night: "N/A",
      Budget_day: "N/A",
      Category: "Industrial",
      Country: "India",
      Created_By: 14.0,
      Location_Description: "Busiest port in Andhra Pradesh.",
      Location_Id: 13,
      Location_Name: "Vizag Port",
      Location_Type: "Outdoor",
      Owner_details: "Vizag Port Authority",
      Permissions: "Limited Access",
      Photo_Path1: "path21.jpg",
      Photo_Path2: "path22.jpg",
      Photo_Path3: "path23.jpg",
      Photo_Path4: "path24.jpg",
      Photo_Path5: "path25.jpg",
      Previous_Films: "N/A",
      Record_Status: "Active",
      Specification: "Major Port",
      State: "Andhra Pradesh",
      Status: "Available",
    },
    {
      Area: "Not Applicable",
      Assigned_To: 15.0,
      Assigned_date: "Mon, 16 Jan 2023 00:00:00 GMT",
      Budget_Night: "N/A",
      Budget_day: "N/A",
      Category: "Scenic",
      Country: "India",
      Created_By: 15.0,
      Location_Description: "Large dam with picturesque surroundings.",
      Location_Id: 14,
      Location_Name: "Nagarjuna Sagar Dam",
      Location_Type: "Outdoor",
      Owner_details: "Telangana Irrigation Dept.",
      Permissions: "Public Access",
      Photo_Path1: "path26.jpg",
      Photo_Path2: "path27.jpg",
      Photo_Path3: "path28.jpg",
      Photo_Path4: "path29.jpg",
      Photo_Path5: "path30.jpg",
      Previous_Films: "N/A",
      Record_Status: "Active",
      Specification: "Irrigation Dam",
      State: "Telangana",
      Status: "Available",
    },
    {
      Area: "Not Applicable",
      Assigned_To: 16.0,
      Assigned_date: "Mon, 02 Jan 2023 00:00:00 GMT",
      Budget_Night: "7000",
      Budget_day: "5000",
      Category: "Historic",
      Country: "India",
      Created_By: 16.0,
      Location_Description: "Luxurious palace turned hotel.",
      Location_Id: 15,
      Location_Name: "Taj Falaknuma Palace",
      Location_Type: "Indoor",
      Owner_details: "Taj Hotels",
      Permissions: "Private Access",
      Photo_Path1: "path31.jpg",
      Photo_Path2: "path32.jpg",
      Photo_Path3: "path33.jpg",
      Photo_Path4: "path34.jpg",
      Photo_Path5: "path35.jpg",
      Previous_Films: "Bajrangi Bhaijaan",
      Record_Status: "Active",
      Specification: "Palace",
      State: "Telangana",
      Status: "Available",
    },
    {
      Area: "",
      Assigned_To: "",
      Assigned_date: "",
      Budget_Night: "",
      Budget_day: "",
      Category: "",
      Country: "",
      Created_By: "",
      Location_Description: "",
      Location_Id: 16,
      Location_Name: " COFFEE SHOP",
      Location_Type: "",
      Owner_details: "",
      Permissions: "",
      Photo_Path1: "",
      Photo_Path2: "",
      Photo_Path3: "",
      Photo_Path4: "",
      Photo_Path5: "",
      Previous_Films: "",
      Record_Status: "",
      Specification: "",
      State: "",
      Status: "",
    },
    {
      Area: "",
      Assigned_To: "",
      Assigned_date: "",
      Budget_Night: "",
      Budget_day: "",
      Category: "",
      Country: "",
      Created_By: "",
      Location_Description: "",
      Location_Id: 17,
      Location_Name: " 74 CHEVY (MOVING)",
      Location_Type: "",
      Owner_details: "",
      Permissions: "",
      Photo_Path1: "",
      Photo_Path2: "",
      Photo_Path3: "",
      Photo_Path4: "",
      Photo_Path5: "",
      Previous_Films: "",
      Record_Status: "",
      Specification: "",
      State: "",
      Status: "",
    },
    {
      Area: "",
      Assigned_To: "",
      Assigned_date: "",
      Budget_Night: "",
      Budget_day: "",
      Category: "",
      Country: "",
      Created_By: "",
      Location_Description: "",
      Location_Id: 18,
      Location_Name: " CHEVY (TRUNK)",
      Location_Type: "",
      Owner_details: "",
      Permissions: "",
      Photo_Path1: "",
      Photo_Path2: "",
      Photo_Path3: "",
      Photo_Path4: "",
      Photo_Path5: "",
      Previous_Films: "",
      Record_Status: "",
      Specification: "",
      State: "",
      Status: "",
    },
    {
      Area: "",
      Assigned_To: "",
      Assigned_date: "",
      Budget_Night: "",
      Budget_day: "",
      Category: "",
      Country: "",
      Created_By: "",
      Location_Description: "",
      Location_Id: 19,
      Location_Name: " APARTMENT BUILDING COURTYARD",
      Location_Type: "",
      Owner_details: "",
      Permissions: "",
      Photo_Path1: "",
      Photo_Path2: "",
      Photo_Path3: "",
      Photo_Path4: "",
      Photo_Path5: "",
      Previous_Films: "",
      Record_Status: "",
      Specification: "",
      State: "",
      Status: "",
    },
    {
      Area: "",
      Assigned_To: "",
      Assigned_date: "",
      Budget_Night: "",
      Budget_day: "",
      Category: "",
      Country: "",
      Created_By: "",
      Location_Description: "",
      Location_Id: 20,
      Location_Name: " RECEPTION AREA (APARTMENT BUILDING)",
      Location_Type: "",
      Owner_details: "",
      Permissions: "",
      Photo_Path1: "",
      Photo_Path2: "",
      Photo_Path3: "",
      Photo_Path4: "",
      Photo_Path5: "",
      Previous_Films: "",
      Record_Status: "",
      Specification: "",
      State: "",
      Status: "",
    },
    {
      Area: "",
      Assigned_To: "",
      Assigned_date: "",
      Budget_Night: "",
      Budget_day: "",
      Category: "",
      Country: "",
      Created_By: "",
      Location_Description: "",
      Location_Id: 21,
      Location_Name: " ELEVATOR",
      Location_Type: "",
      Owner_details: "",
      Permissions: "",
      Photo_Path1: "",
      Photo_Path2: "",
      Photo_Path3: "",
      Photo_Path4: "",
      Photo_Path5: "",
      Previous_Films: "",
      Record_Status: "",
      Specification: "",
      State: "",
      Status: "",
    },
    {
      Area: "",
      Assigned_To: "",
      Assigned_date: "",
      Budget_Night: "",
      Budget_day: "",
      Category: "",
      Country: "",
      Created_By: "",
      Location_Description: "",
      Location_Id: 22,
      Location_Name: " APARTMENT BUILDING HALLWAY",
      Location_Type: "",
      Owner_details: "",
      Permissions: "",
      Photo_Path1: "",
      Photo_Path2: "",
      Photo_Path3: "",
      Photo_Path4: "",
      Photo_Path5: "",
      Previous_Films: "",
      Record_Status: "",
      Specification: "",
      State: "",
      Status: "",
    },
    {
      Area: "",
      Assigned_To: "",
      Assigned_date: "",
      Budget_Night: "",
      Budget_day: "",
      Category: "",
      Country: "",
      Created_By: "",
      Location_Description: "",
      Location_Id: 23,
      Location_Name: " APARTMENT (ROOM 49)",
      Location_Type: "",
      Owner_details: "",
      Permissions: "",
      Photo_Path1: "",
      Photo_Path2: "",
      Photo_Path3: "",
      Photo_Path4: "",
      Photo_Path5: "",
      Previous_Films: "",
      Record_Status: "",
      Specification: "",
      State: "",
      Status: "",
    },
    {
      Area: "",
      Assigned_To: "",
      Assigned_date: "",
      Budget_Night: "",
      Budget_day: "",
      Category: "",
      Country: "",
      Created_By: "",
      Location_Description: "",
      Location_Id: 24,
      Location_Name: " CAR (MOVING)",
      Location_Type: "",
      Owner_details: "",
      Permissions: "",
      Photo_Path1: "",
      Photo_Path2: "",
      Photo_Path3: "",
      Photo_Path4: "",
      Photo_Path5: "",
      Previous_Films: "",
      Record_Status: "",
      Specification: "",
      State: "",
      Status: "",
    },
    {
      Area: "",
      Assigned_To: "",
      Assigned_date: "",
      Budget_Night: "",
      Budget_day: "",
      Category: "",
      Country: "",
      Created_By: "",
      Location_Description: "",
      Location_Id: 25,
      Location_Name: " SALLY LeROYS",
      Location_Type: "",
      Owner_details: "",
      Permissions: "",
      Photo_Path1: "",
      Photo_Path2: "",
      Photo_Path3: "",
      Photo_Path4: "",
      Photo_Path5: "",
      Previous_Films: "",
      Record_Status: "",
      Specification: "",
      State: "",
      Status: "",
    },
  ],
  status: 200,
};

module.exports = tempLocationApproveData;
