const characterToArtistMapping = {
  message: "successfully",
  result: {
    character_data: {
      Acting_Age: 35,
      Actual_Age: 45,
      Address: "7 Ravi Teja Street",
      Area: "Hyderabad",
      Arts: "Painting",
      Assigned_To: 7,
      Assigned_date: "Wed, 18 Oct 2023 00:00:00 GMT",
      Athlethics: "Cricket",
      Character_Name: "Ravi Teja",
      Character_Type: "Actor",
      Character_id: 11,
      Country: "India",
      Created_By: 1,
      Created_on: "Sun, 01 Oct 2023 00:00:00 GMT",
      Dance: "Hip-hop",
      Date_Of_Birth: "Wed, 26 Jan 1977 00:00:00 GMT",
      Description: "Mass Maharaja known for his energetic roles.",
      Email_Id: "raviteja@example.com",
      Eye_Colour: "Brown",
      Film_Exp: "20 years",
      Films_Played: "35 films",
      Full_Name: "Ravi Shankar Raju Bhupatiraju",
      Gender: "Male",
      Hair_colour: "Black",
      Height: "6",
      Key_Features: "Stubble beard",
      Mobile_No1: "1111111111",
      Mobile_No2: "2222222222",
      Music: "Singing",
      Photo_Path1: "/photos/raviteja1.jpg",
      Photo_Path2: "/photos/raviteja2.jpg",
      Photo_Path3: "/photos/raviteja3.jpg",
      Record_Status: true,
      Roles_Played: "Lead roles in action and comedy films",
      State: "Telangana",
      Status: "Active",
      Submitted: "Yes",
      Weight: "175",
      seleted_actor_id: null,
    },
  },
  status: 200,
};

exports.characterToArtistMapping = characterToArtistMapping;
