const tempArtistsData = {
  message: "records fetched successfully!",
  result: [
    {
      ActingAge: 40.0,
      ActorName: "Prabhas",
      Address: "Hyderabad",
      Athletics: false,
      DanceAndMusic: true,
      Email: "prabhas@email.com",
      EyeColour: "Brown",
      FilmExperience: 20.0,
      Films: "Baahubali",
      Gender: "Male",
      HairColour: "Black",
      Height: 6.2,
      Language: "Telugu",
      PerformingArts: true,
      PhoneNumber: "123-456-7890",
      Role: "Amarendra Baahubali",
      Roles: "Lead",
      actor_id: 1,
      character_id: 1.0,
    },
    {
      ActingAge: 38.0,
      ActorName: "Anushka Shetty",
      Address: "Mangaluru",
      Athletics: false,
      DanceAndMusic: true,
      Email: "anushka@email.com",
      EyeColour: "Hazel",
      FilmExperience: 18.0,
      Films: "Arundhati",
      Gender: "Female",
      HairColour: "Black",
      Height: 5.9,
      Language: "Telugu",
      PerformingArts: true,
      PhoneNumber: "987-654-3210",
      Role: "Arundhati",
      Roles: "Lead",
      actor_id: 2,
      character_id: 2.0,
    },
    {
      ActingAge: 37.0,
      ActorName: "Allu Arjun",
      Address: "Hyderabad",
      Athletics: true,
      DanceAndMusic: true,
      Email: "alluarjun@email.com",
      EyeColour: "Brown",
      FilmExperience: 22.0,
      Films: "Arya",
      Gender: "Male",
      HairColour: "Black",
      Height: 5.9,
      Language: "Telugu",
      PerformingArts: true,
      PhoneNumber: "555-555-5555",
      Role: "Arya",
      Roles: "Lead",
      actor_id: 3,
      character_id: 3.0,
    },
    {
      ActingAge: 33.0,
      ActorName: "Samantha Akkineni",
      Address: "Chennai",
      Athletics: false,
      DanceAndMusic: true,
      Email: "samantha@email.com",
      EyeColour: "Green",
      FilmExperience: 15.0,
      Films: "Ye Maaya Chesave",
      Gender: "Female",
      HairColour: "Brown",
      Height: 5.7,
      Language: "Telugu",
      PerformingArts: true,
      PhoneNumber: "999-888-7777",
      Role: "Jessie Thekekuttu",
      Roles: "Lead",
      actor_id: 4,
      character_id: 4.0,
    },
    {
      ActingAge: 45.0,
      ActorName: "Mahesh Babu",
      Address: "Hyderabad",
      Athletics: false,
      DanceAndMusic: false,
      Email: "mahesh@email.com",
      EyeColour: "Brown",
      FilmExperience: 25.0,
      Films: "Srimanthudu",
      Gender: "Male",
      HairColour: "Black",
      Height: 6.0,
      Language: "Telugu",
      PerformingArts: true,
      PhoneNumber: "444-333-2222",
      Role: "Harsha Vardhan",
      Roles: "Lead",
      actor_id: 5,
      character_id: 5.0,
    },
    {
      ActingAge: 31.0,
      ActorName: "Tamannaah Bhatia",
      Address: "Mumbai",
      Athletics: false,
      DanceAndMusic: true,
      Email: "tamannaah@email.com",
      EyeColour: "Brown",
      FilmExperience: 20.0,
      Films: "Baahubali",
      Gender: "Female",
      HairColour: "Black",
      Height: 5.6,
      Language: "Telugu",
      PerformingArts: true,
      PhoneNumber: "777-666-5555",
      Role: "Avanthika",
      Roles: "Lead",
      actor_id: 6,
      character_id: 6.0,
    },
    {
      ActingAge: 38.0,
      ActorName: "Jr. NTR",
      Address: "Hyderabad",
      Athletics: true,
      DanceAndMusic: false,
      Email: "jrntr@email.com",
      EyeColour: "Brown",
      FilmExperience: 28.0,
      Films: "Janatha Garage",
      Gender: "Male",
      HairColour: "Black",
      Height: 5.1,
      Language: "Telugu",
      PerformingArts: true,
      PhoneNumber: "111-222-3333",
      Role: "Anand",
      Roles: "Lead",
      actor_id: 7,
      character_id: 7.0,
    },
    {
      ActingAge: 34.0,
      ActorName: "Kajal Aggarwal",
      Address: "Mumbai",
      Athletics: false,
      DanceAndMusic: false,
      Email: "kajal@email.com",
      EyeColour: "Hazel",
      FilmExperience: 18.0,
      Films: "Magadheera",
      Gender: "Female",
      HairColour: "Brown",
      Height: 5.5,
      Language: "Telugu",
      PerformingArts: true,
      PhoneNumber: "999-888-7777",
      Role: "Mitravinda",
      Roles: "Lead",
      actor_id: 8,
      character_id: 8.0,
    },
    {
      ActingAge: 46.0,
      ActorName: "Ravi Teja",
      Address: "Hyderabad",
      Athletics: true,
      DanceAndMusic: true,
      Email: "raviteja@email.com",
      EyeColour: "Brown",
      FilmExperience: 30.0,
      Films: "Kick",
      Gender: "Male",
      HairColour: "Black",
      Height: 5.11,
      Language: "Telugu",
      PerformingArts: true,
      PhoneNumber: "555-444-3333",
      Role: "Kalyan",
      Roles: "Lead",
      actor_id: 9,
      character_id: 9.0,
    },
    {
      ActingAge: 26.0,
      ActorName: "Rashmika Mandanna",
      Address: "Bangalore",
      Athletics: false,
      DanceAndMusic: true,
      Email: "rashmika@email.com",
      EyeColour: "Brown",
      FilmExperience: 10.0,
      Films: "Geetha Govindam",
      Gender: "Female",
      HairColour: "Black",
      Height: 5.6,
      Language: "Telugu",
      PerformingArts: true,
      PhoneNumber: "777-666-5555",
      Role: "Geetha",
      Roles: "Lead",
      actor_id: 10,
      character_id: 10.0,
    },
    {
      ActingAge: 38.0,
      ActorName: "Nani",
      Address: "Hyderabad",
      Athletics: false,
      DanceAndMusic: true,
      Email: "nani@email.com",
      EyeColour: "Brown",
      FilmExperience: 22.0,
      Films: "Bhale Bhale Magadivoy",
      Gender: "Male",
      HairColour: "Black",
      Height: 5.9,
      Language: "Telugu",
      PerformingArts: true,
      PhoneNumber: "123-987-6543",
      Role: "Lucky",
      Roles: "Lead",
      actor_id: 11,
      character_id: 11.0,
    },
    {
      ActingAge: 34.0,
      ActorName: "Shruti Haasan",
      Address: "Chennai",
      Athletics: false,
      DanceAndMusic: true,
      Email: "shruti@email.com",
      EyeColour: "Hazel",
      FilmExperience: 16.0,
      Films: "Gabbar Singh",
      Gender: "Female",
      HairColour: "Brown",
      Height: 5.7,
      Language: "Telugu",
      PerformingArts: true,
      PhoneNumber: "999-555-3333",
      Role: "Bhagyalakshmi",
      Roles: "Lead",
      actor_id: 12,
      character_id: 12.0,
    },
    {
      ActingAge: 36.0,
      ActorName: "Ram Charan",
      Address: "Hyderabad",
      Athletics: true,
      DanceAndMusic: true,
      Email: "ramcharan@email.com",
      EyeColour: "Brown",
      FilmExperience: 26.0,
      Films: "Magadheera",
      Gender: "Male",
      HairColour: "Black",
      Height: 5.8,
      Language: "Telugu",
      PerformingArts: true,
      PhoneNumber: "111-222-3333",
      Role: "Harsha",
      Roles: "Lead",
      actor_id: 13,
      character_id: 13.0,
    },
    {
      ActingAge: 28.0,
      ActorName: "Keerthy Suresh",
      Address: "Chennai",
      Athletics: false,
      DanceAndMusic: false,
      Email: "keerthy@email.com",
      EyeColour: "Brown",
      FilmExperience: 10.0,
      Films: "Mahanati",
      Gender: "Female",
      HairColour: "Black",
      Height: 5.4,
      Language: "Telugu",
      PerformingArts: true,
      PhoneNumber: "777-555-3333",
      Role: "Savitri",
      Roles: "Lead",
      actor_id: 14,
      character_id: 14.0,
    },
    {
      ActingAge: 50.0,
      ActorName: "Venkatesh Daggubati",
      Address: "Hyderabad",
      Athletics: false,
      DanceAndMusic: false,
      Email: "venkatesh@email.com",
      EyeColour: "Brown",
      FilmExperience: 32.0,
      Films: "Drushyam",
      Gender: "Male",
      HairColour: "Black",
      Height: 6.1,
      Language: "Telugu",
      PerformingArts: true,
      PhoneNumber: "123-555-7777",
      Role: "Rambabu",
      Roles: "Lead",
      actor_id: 15,
      character_id: 15.0,
    },
    {
      ActingAge: NaN,
      ActorName: "Srivatsa",
      Address: null,
      Athletics: null,
      DanceAndMusic: null,
      Email: null,
      EyeColour: null,
      FilmExperience: NaN,
      Films: null,
      Gender: "Male",
      HairColour: null,
      Height: NaN,
      Language: null,
      PerformingArts: null,
      PhoneNumber: null,
      Role: null,
      Roles: null,
      actor_id: 19,
      character_id: NaN,
    },
  ],
  status: 200,
};

module.exports = tempArtistsData;
