const tempSearchCharacterData = {
  count_list: [],
  message: "successfully",
  result: [
    {
      Acting_Age: 35,
      Actual_Age: 42,
      Address: "1 Prabhas Street",
      Area: "Hyderabad",
      Arts: "Painting",
      Assigned_To: 5,
      Assigned_date: "Tue, 03 Oct 2023 12:00:00 GMT",
      Athlethics: "Cricket",
      Character_Name: "Prabhas",
      Character_Type: "Actor",
      Character_id: 5,
      Country: "India",
      Created_By: 5,
      Created_on: "Mon, 02 Oct 2023 08:21:00 GMT",
      Dance: "Ballet",
      Date_Of_Birth: "Thu, 23 Oct 1980 00:00:00 GMT",
      Description: "Renowned Tollywood actor famous for Baahubali series.",
      Email_Id: "prabhas@example.com",
      Eye_Colour: "Brown",
      Features_Required: "Main Character",
      Film_Exp: "18 years",
      Films_Played: "25 films",
      Full_Name: "Prabhas Raju Uppalapati",
      Gender: "Male",
      Hair_colour: "Black",
      Height: "6",
      Key_Features: "Tattoo on right arm",
      Mobile_No1: "1234567890",
      Mobile_No2: "0987654321",
      Music: "Guitar",
      No_Of_Scenes: 3,
      Photo_Path1: "/photos/prabhas1.jpg",
      Photo_Path2: "/photos/prabhas2.jpg",
      Photo_Path3: "/photos/prabhas3.jpg",
      Production_id: 14,
      Record_Status: true,
      Roles_Played: "Lead roles in blockbuster films",
      Scene_Character_Id: 5,
      Scene_Id: 55,
      Screen_Time_Minutes: 22,
      Script_pages: "21-25",
      Shoot_Time_Minutes: 110,
      State: "Telangana",
      Status: "Pending",
      Submitted: "Yes",
      Weight: "200",
    },
    {
      Acting_Age: 28,
      Actual_Age: 40,
      Address: "6 Anushka Street",
      Area: "Hyderabad",
      Arts: "Painting",
      Assigned_To: 10,
      Assigned_date: "Tue, 03 Oct 2023 12:00:00 GMT",
      Athlethics: "Yoga",
      Character_Name: "Anushka Shetty",
      Character_Type: "Actress",
      Character_id: 10,
      Country: "India",
      Created_By: 10,
      Created_on: "Mon, 02 Oct 2023 08:21:00 GMT",
      Dance: "Ballet",
      Date_Of_Birth: "Sat, 07 Nov 1981 00:00:00 GMT",
      Description: "Leading lady in Telugu and Tamil cinema.",
      Email_Id: "anushka@example.com",
      Eye_Colour: "Brown",
      Features_Required: "Supporting Character",
      Film_Exp: "15 years",
      Films_Played: "20 films",
      Full_Name: "Sweety Shetty",
      Gender: "Female",
      Hair_colour: "Black",
      Height: "6",
      Key_Features: "Smile and dimples",
      Mobile_No1: "5555555555",
      Mobile_No2: "6666666666",
      Music: "Singing",
      No_Of_Scenes: 2,
      Photo_Path1: "/photos/anushka1.jpg",
      Photo_Path2: "/photos/anushka2.jpg",
      Photo_Path3: "/photos/anushka3.jpg",
      Production_id: 14,
      Record_Status: true,
      Roles_Played: "Lead roles in epic and historical films",
      Scene_Character_Id: 10,
      Scene_Id: 1010,
      Screen_Time_Minutes: 12,
      Script_pages: "46-50",
      Shoot_Time_Minutes: 75,
      State: "Telangana",
      Status: "Assigned",
      Submitted: "Yes",
      Weight: "160",
    },
    {
      Acting_Age: 35,
      Actual_Age: 45,
      Address: "7 Ravi Teja Street",
      Area: "Hyderabad",
      Arts: "Painting",
      Assigned_To: 11,
      Assigned_date: "Tue, 03 Oct 2023 12:00:00 GMT",
      Athlethics: "Cricket",
      Character_Name: "Ravi Teja",
      Character_Type: "Actor",
      Character_id: 11,
      Country: "India",
      Created_By: 11,
      Created_on: "Mon, 02 Oct 2023 08:21:00 GMT",
      Dance: "Hip-hop",
      Date_Of_Birth: "Wed, 26 Jan 1977 00:00:00 GMT",
      Description: "Mass Maharaja known for his energetic roles.",
      Email_Id: "raviteja@example.com",
      Eye_Colour: "Brown",
      Features_Required: "Main Character",
      Film_Exp: "20 years",
      Films_Played: "35 films",
      Full_Name: "Ravi Shankar Raju Bhupatiraju",
      Gender: "Male",
      Hair_colour: "Black",
      Height: "6",
      Key_Features: "Stubble beard",
      Mobile_No1: "1111111111",
      Mobile_No2: "2222222222",
      Music: "Singing",
      No_Of_Scenes: 4,
      Photo_Path1: "/photos/raviteja1.jpg",
      Photo_Path2: "/photos/raviteja2.jpg",
      Photo_Path3: "/photos/raviteja3.jpg",
      Production_id: 14,
      Record_Status: true,
      Roles_Played: "Lead roles in action and comedy films",
      Scene_Character_Id: 11,
      Scene_Id: 11,
      Screen_Time_Minutes: 28,
      Script_pages: "51-55",
      Shoot_Time_Minutes: 140,
      State: "Telangana",
      Status: "Pending",
      Submitted: "Yes",
      Weight: "175",
    },
  ],
  status: 200,
};

module.exports = tempSearchCharacterData;

const mock_tempSearchCharacterData = [
  {
    id: 1,
    title: "Tony Stark",
    status: "In Progress",
    characterDetails: {
      role: "Main",
      gender: "M",
      age: "45",
    },
    showStatusButton: false,
    showSelectButton: true,
    showMoreButton: true,
    description:
      "Tony Stark, also known as Iron Man, is a brilliant inventor and billionaire playboy. He's the genius behind the Iron Man suit and fights crime with his advanced technology.",
    keyFeatures: "Dark hair, well-groomed beard, charismatic look",
  },
  {
    id: 2,
    title: "Steve Rogers",
    status: "Completed",
    characterDetails: {
      role: "Main",
      gender: "M",
      age: "95",
    },
    showStatusButton: false,
    showSelectButton: true,
    showMoreButton: true,
    description:
      "Steve Rogers, also known as Captain America, is a super-soldier with enhanced strength, agility, and leadership skills. He's a symbol of heroism and justice.",
    keyFeatures: "Square jaw, athletic build, clean-cut appearance",
  },
  {
    id: 3,
    title: "Natasha Romanoff",
    status: "In Progress",
    characterDetails: {
      role: "Main",
      gender: "F",
      age: "30",
    },
    showStatusButton: false,
    showSelectButton: true,
    showMoreButton: true,
    description:
      "Natasha Romanoff, also known as Black Widow, is a skilled spy and assassin. She's highly trained in hand-to-hand combat and espionage.",
    keyFeatures: "Red hair, athletic build, striking and confident look",
  },
  {
    id: 4,
    title: "Bruce Banner",
    status: "Scheduled",
    characterDetails: {
      role: "Main",
      gender: "M",
      age: "35",
    },
    showStatusButton: false,
    showSelectButton: true,
    showMoreButton: true,
    description:
      "Bruce Banner, also known as the Hulk, is a brilliant scientist who transforms into a green, giant, and incredibly strong creature when he gets angry.",
    keyFeatures: "Green skin, muscular build, intense expression",
  },
  {
    id: 5,
    title: "Diana Prince",
    status: "In Progress",
    characterDetails: {
      role: "Main",
      gender: "F",
      age: "2000",
    },
    showStatusButton: false,
    showSelectButton: true,
    showMoreButton: true,
    description:
      "Diana Prince, also known as Wonder Woman, is an Amazonian warrior with superhuman strength, agility, and a sense of justice.",
    keyFeatures:
      "Amazonian warrior attire, confident demeanor, striking appearance",
  },
  {
    id: 6,
    title: "Barry Allen",
    status: "Completed",
    characterDetails: {
      role: "Main",
      gender: "M",
      age: "30",
    },
    showStatusButton: false,
    showSelectButton: true,
    showMoreButton: true,
    description:
      "Barry Allen, also known as The Flash, is a superhero with superhuman speed. He can move at incredible velocities and has a strong sense of heroism.",
    keyFeatures: "Red costume, lightning bolt emblem, energetic look",
  },
  {
    id: 7,
    title: "Arthur Curry",
    status: "In Progress",
    characterDetails: {
      role: "Main",
      gender: "M",
      age: "35",
    },
    showStatusButton: false,
    showSelectButton: true,
    showMoreButton: true,
    description:
      "Arthur Curry, also known as Aquaman, is a superhero with the ability to communicate with marine life and superhuman strength. He protects the oceans and the world from threats.",
    keyFeatures: "Aquaman costume, sea-themed appearance, regal presence",
  },
  {
    id: 8,
    title: "Carol Danvers",
    status: "Scheduled",
    characterDetails: {
      role: "Main",
      gender: "F",
      age: "30",
    },
    showStatusButton: false,
    showSelectButton: true,
    showMoreButton: true,
    description:
      "Carol Danvers, also known as Captain Marvel, is a superhero with incredible cosmic powers. She's a fierce protector of the universe.",
    keyFeatures: "Captain Marvel suit, cosmic energy aura, determined look",
  },
  {
    id: 9,
    title: "Peter Parker",
    status: "In Progress",
    characterDetails: {
      role: "Main",
      gender: "M",
      age: "30",
    },
    showStatusButton: false,
    showSelectButton: true,
    showMoreButton: true,
    description:
      "Peter Parker, also known as Spider-Man, is a superhero with spider-like abilities. He swings through the city and fights crime with agility and web-shooting gadgets.",
    keyFeatures: "Spider-Man suit, acrobatic moves, youthful appearance",
  },
];
